image: golang

stages:
  - lint
  - test

variables:
  GO111MODULE: "on"

lint:
  stage: lint
  before_script:
    - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0"
  script: 
    - "golangci-lint run"

test:
  stage: test
  script: 
    - "go test ./... -coverprofile cover.out -race"
    - "go tool cover -func cover.out"
    - "go test -bench=. ./..."
