image: golang

stages:
  - lint
  - test

variables:
  GO111MODULE: "on"

.merge_requests: &merge_requests
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never

lint:
  stage: lint
  before_script:
    - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0"
  script: 
    - "golangci-lint run"
  <<: *merge_requests

lint:tasks:
  stage: lint
  before_script:
    - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.31.0"
  script: 
    - "golangci-lint run -E godox"
  rules:
    - if: $CI_MERGE_REQUEST_ID && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH
      when: always
    - if: $CI_MERGE_REQUEST_ID
      allow_failure: true
      when: always
    - when: never

test:
  stage: test
  script: 
    - "go test ./... -coverprofile cover.out -race"
    - "go tool cover -func cover.out"
    - "go test -bench=. ./..."
  <<: *merge_requests