variables:
  GO111MODULE: "on"

test:
  image: golang

  before_script:
    - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0"
  script: 
    - "go test ./... -coverprofile cover.out -race"
    - "go tool cover -func cover.out"
    - "golangci-lint run" 
