run:
  modules-download-mode: readonly

linters:
  enable:
    - maligned
    - golint
    - gocritic
    - gosec
    - misspell
    - prealloc
    - godox

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - opinionated
  maligned:
    suggect-new: true
  misspell:
    locale: UK
  prealloc:
