run:
  modules-download-mode: readonly

linters:
  enable:
    - maligned
    - golint
    - gocritic
    - gosec
    - misspell
    - prealloc
    - godox
    - unparam
    - godot
    - govet

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec

linters-settings:
  gocritic:
    enabled-tags:
      - performance
      - opinionated
      - experimental
      - style
      - diagnostic
    disabled-checks:
      - ptrToRefParam
  maligned:
    suggest-new: true
  misspell:
    locale: UK
  prealloc:
